//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERADDRESS
    {
        public int ID { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
    }
}
