//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKS
    {
        public int ID { get; set; }
        public string STOCKCODE { get; set; }
        public string NAME { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    }
}
